### ISSUE TITLE
Add release

### ISSUE THREAD

**Issue by pspeter3** [cortesi/modd#1]
If you suggest using `modd` with `devd`, https://github.com/cortesi/devd/issues/18, could you please push a release like you did for devd?

**Comment by cortesi** [comment]
Hi there. I will definitely do that as soon as I have something ready - modd is not quite at 0.1 level yet. I'm also still undecided about the exact relationship between modd and devd, and how much of the modd functionality can sensibly be directly in devd itself.

I've had a busy few weeks, but should be able to return to this soon.

**Comment by cortesi** [comment]
modd v0.1 should be ready in the next week or so.  I've honed in on a design, and we're close to ready.
