### ISSUE TITLE
--daemon flag?

### ISSUE THREAD

**Issue by cameronelliott** [cortesi/modd#104]
I really really really dig modd.

One thing I have noticed, is sometimes when I am developing and iterating, I want to change the daemon: lines a lot, I wonder if there would be interest in a '--daemon <command>' flag which allowed one to setup a quick daemon overriding the modd.conf file?
Although I guess there is the question of what file pattrns to watch.

Any ideas?

**Comment by wader** [comment]
Not very nice but i've used the fact that modd uses a shell interpreter a few time, so something like this might be ok?
```
{
    daemon: $DAEOMON
}
```
and then run:
```
DAEOMON="echo hello" modd -f test.conf
```

**Comment by cameronelliott** [comment]
Hey! That actually works, thank you for pointing that out!

**Comment by wader** [comment]
No problem, im a big modd fan also :)
