### ISSUE TITLE
Is this project unmaintained? Are there suggested alternatives?

### ISSUE THREAD

**Issue by jesselang** [cortesi/modd#120]
Hello. I really have enjoyed using this project up until recently when it was no longer available on brew due to #119. Is this project no longer maintained? Is someone interested in maintaining it? Should it be archived? Are there suggested alternatives? Thanks much!

**Comment by joncalhoun** [comment]
I would suggest installing via Go. As long as you have a mostly recent version of Go, the command should be something like:

```
go install github.com/cortesi/modd/cmd/modd@latest
```

The docs need updated to reflect this, but otherwise I haven't had any issues using the library.

**Comment by jesselang** [comment]
Thanks @joncalhoun, as I mentioned [here](https://github.com/cortesi/modd/issues/119#issuecomment-1334059068), the `go install` method produces compilation errors. Any help would be much appreciated. Thanks!

**Comment by jesselang** [comment]
I was able to build modd with CGO enabled. But I am still curious about the project status, etc. I've tried another popular tool, but it doesn't fulfill my desire for simplicity that modd does.

**Comment by joncalhoun** [comment]
What did you have in mind?

Personally, I think the project works pretty well as-is, so in the immediate future I don't think many, if any, features should be added. My reasoning here is that adding new features adds complexity, and in my experience most new maintainers don't understand this fully until they say "Yes" to too many features and end up with a project that is much harder to maintain. 

I also don't know this project very well, and I don't have the capacity to review large changes that aren't absolutely necessary. 

If you want to get involved in just making sure things work and are documented accurately, that is likely possible.

If you want to fix the `brew` install process, I can't really speak to whether that is possible. I don't know what permissions would need transferred, and I don't have those permissions anyway. 

I am very likely going to just close all existing issues at some point and be very picky about what issues are considered for future work, with a high priority on bug fixes, and virtually no feature requests being done for the time being.

**Comment by jesselang** [comment]
Thanks for your thoughtful response, @joncalhoun, and thank you for your involvement with this project that I find very valuable!

I agree with your opinion: this project works very well as-is. I appreciate how simple it is to use. I'm not interested in new features. I am interested a "healthy" project: stable working and testable software with build/test/release automation, fresh releases with up-to-date dependencies, clear and accurate documentation, issues and PRs that aren't stale, etc.

I would love to get the `brew` install process back up and running if possible, but I understand if that's not feasible.

In any case, let me know how I can help with this project. Thanks!

**Comment by joncalhoun** [comment]
You are welcome to look into the brew stuff. Maybe I am wrong and someone else can update it with a PR. I don't really know how brew manages package ownership.

**Comment by jesselang** [comment]
I've done a bit of research, and I think a fresh release should get us half way there. https://github.com/cortesi/modd/issues/119#issuecomment-1368143067
