### ISSUE TITLE
'FSEventStreamScheduleWithRunLoop' is deprecated: first deprecated in macOS 13.0 - Use FSEventStreamSetDispatchQueue instead. [-Wdeprecated-declarations]

### ISSUE THREAD

**Issue by chocnut** [cortesi/modd#126]
Running go install `github.com/cortesi/modd/cmd/modd@latest` or `CGO_ENABLED=1 go install github.com/cortesi/modd/cmd/modd@latest` throws an error and `modd` command not found even restarting iTerm

Arch details:
➜  ~ arch
arm64

➜  ~ uname -a
Darwin MacBook-Pro.local 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000 arm64

**Comment by bobfirestone** [comment]
Getting the same thing. This is the full error message I am getting on a m1 Mac running the latest macOS `13.3.1 (a) (22E772610a)`.

> cgo-gcc-prolog:217:2: warning: 'FSEventStreamScheduleWithRunLoop' is deprecated: first deprecated in macOS 13.0 - Use FSEventStreamSetDispatchQueue instead. [-Wdeprecated-declarations]
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/FSEvents.framework/Headers/FSEvents.h:1138:1: note: 'FSEventStreamScheduleWithRunLoop' has been explicitly marked deprecated here

**Comment by joncalhoun** [comment]
Try the latest version. See if it works. It should now that I updated the dependencies of moddwatch and modd to use a newer version of the notify lib.

**Comment by bobfirestone** [comment]
👍 that works
