### ISSUE TITLE
zsh: command not found: modd on M2

### ISSUE THREAD

**Issue by akintaylor** [cortesi/modd#127]
I followed the readme and I get this error.
`zsh: command not found: modd`

Now I do not even know where the binary is located

**Comment by wader** [comment]
You used go install? Then the binary will end up in GOBIN. Try run go env GOBIN to see where it is

**Comment by akintaylor** [comment]
Ah, thank you, @wader. Well, my GOBIN is an empty string. 
`GOBIN=""`

**Comment by wader** [comment]
Ah sorry try look in `$(go env GOPATH)/bin`

**Comment by akintaylor** [comment]
@wader Thanks for helping me with this. 

The issue here was the go on `PATH` did not match with the `GOPATH` and hence my `GOBIN` was referencing the wrong path for installed packages. False alarm and will close this. Cheers

**Comment by akintaylor** [comment]
@wader Thanks for helping me with this.

The issue here was the go on PATH did not match with the GOPATH and hence my GOBIN was referencing the wrong path for installed packages. False alarm and will close this. Cheers
