### ISSUE TITLE
Binary file is not being found when running modd.

### ISSUE THREAD

**Issue by GMcC-94** [cortesi/modd#128]
Conf file:
`**/*.go {
    prep: go test @dirmods
}

**/*.go !**/*_test.go **/*.gohtml {
    prep: go build -o bin/webapp
    daemon +sigterm: ./bin/webapp
}`

`$ modd
15:07:50: prep: go test "./cmd/exp" "./controllers" "./" "./templates" "./views"
?       github.com/gmcc94/web-dev/cmd/exp       [no test files]
?       github.com/gmcc94/web-dev/controllers   [no test files]
?       github.com/gmcc94/web-dev       [no test files]
?       github.com/gmcc94/web-dev/templates     [no test files]
?       github.com/gmcc94/web-dev/views [no test files]        
>> done (915.5204ms)
15:07:51: prep: go build -o bin/webapp
>> done (788.5459ms)
15:07:52: daemon: +sigterm: ./bin/webapp
>> starting...
not found
exited: exit status 1       
>> restart backoff... 1000ms
>> starting...
not found
exited: exit status 1       
>> restart backoff... 2000ms
>> stopping`

**Comment by GMcC-94** [comment]
My assumption is sigterm is not supported on windows, but I'm unable to find a workaround

**Comment by joncalhoun** [comment]
Check if the file being created has a .exe extension. If so you may need to
update the command that runs your code. I believe windows always adds that
extension.

**Comment by GMcC-94** [comment]
Adding the .exe to the end of the file fixed the problem. Thanks for your help
