### ISSUE TITLE
go web development on windows with modd

### ISSUE THREAD

**Issue by yoava333** [cortesi/modd#13]
I'm trying to use modd for web development on windows:

my modd.conf is:
# basic config

@shell = exec

*_/_.go {
    prep: go build -o tmp/server.exe -v
    daemon +sigkill: ./tmp/server.exe
}

I'm getting this error:
open tmp/server.exe: The process cannot access the file because it is being used by another process.

I've looked with procmon, and it seems that go is unable to rename the file because it's still running.
on windows it's not possible to overwrite an executable currently running.

**Comment by cortesi** [comment]
That's interesting - thanks for reporting the issue. I can think of a lot of inelegant ways to solve this (especially if you did have a shell rather than using exec), but I'd like to come up with something better. Let me ponder it.

**Comment by frederikhors** [comment]
@yoava333 it works good to me with this and anything else:

```
**/*.go {
    daemon: go run .
}
```

**Comment by cortesi** [comment]
Some time has passed since this issue was reported, and I can't reproduce it. Please let me know if you still see the problem.
