### ISSUE TITLE
Support TERM=dumb

### ISSUE THREAD

**Issue by mjibson** [cortesi/modd#17]
My terminal doesn't support colors or other special characters that flag the terminal to do things. I get stuff like this:

![term](https://cloud.githubusercontent.com/assets/41181/13691076/d1b3b05c-e703-11e5-8be9-ada96411bb5e.png)

My $TERM is set to `dumb`, which is the standard value to disable this stuff. Is it possible to support these terminals?

**Comment by cortesi** [comment]
Hi there. Thanks for reporting this. I'd accept a patch to do this if you wanted to have a crack at it. We should also add a command-line flag to turn off color output, in-line with the matching flag in devd.
