### ISSUE TITLE
don't die when prep commands fail on first run

### ISSUE THREAD

**Issue by josharian** [cortesi/modd#18]
When modd first starts up, if the prep commands fail, modd exits. This is frustrating, because it means I have to get everything into a good state (tests passing, etc.) before I can actually use modd. Once modd has done a successful round of prep commands, it no longer exits when prep commands fail. I could work around it with #7, I guess, but I'd rather not have to. Why is it the way it is? Are you open to it changing? If so, I can try to pull together a PR.

**Comment by cortesi** [comment]
Hi Josh. I'd definitely appreciate a PR changing this - it's just something I haven't gotten around to. The right behaviour here requires a bit of work. 

On first run, we execute all of the prep commands in all blocks. If we fail part of the way through the first run, some prep commands that daemons and users might expect may not have run. For instance, I often create directories and so forth whose absence will cause daemons to fail. So, one arguably correct behaviour might be to stop execution of the prep commands, defer starting up daemons, wait for another change, re-try executing the first-run prep commands, and then start up daemons only if the first-run sequence succeeds.
