### ISSUE TITLE
go get fails

### ISSUE THREAD

**Issue by robmuh** [cortesi/modd#21]
go version go1.5 darwin/amd64

```
./main.go:50: kingpin.CommandLine.HelpFlag undefined (type *kingpin.Application has no field or method HelpFlag)
```

**Comment by homburg** [comment]
Seems there's breaking changes in kingpin.v2 on gopkg.in

You can build it in go 1.5 with:

```bash
$ GO15VENDOREXPERIMENT=1 go get github.com/cortesi/modd
```

**Comment by cortesi** [comment]
Closing - @homburg's response is correct. Please do re-open if you're still having issues. Thanks for reporting.
