### ISSUE TITLE
Reap defunct processes

### ISSUE THREAD

**Issue by wader** [cortesi/modd#23]
Hi, im using modd as a init process in a docker container and just noticed that there are a bunch of defunct processes hanging around (in my case dropbox processes). I've been looking around in the logs but can't really determine if they are exited or crashes processes started by modd or by dropbox itself.
My guess is that there are processes started by other processes so modd would have to wait to reap them i guess?
Let me know if this is total misuse of modd 😄  and I if you want help i could try to fix it.
Thanks for modd and devd btw!

**Comment by wader** [comment]
Maybe the sanest solution for a container is to start modd via [tini](https://github.com/krallin/tini) instead. It seems to work fine.

To support this in modd i guess there needs to be some kind of central synchronized process wait or at startup fork off a process doing the modd stuff and let the parent process do reap waiting.

Im fine closing this if you think it is too messy and or out of scope for modd.

**Comment by cortesi** [comment]
Interesting - running modd as PID 0 is not a use case that I've previously considered. I do think using one of the cut-down init project is probably the way to go (I've used https://github.com/Yelp/dumb-init). 

So, I'm not against having this feature in modd, but it's fiddly to get right and probably a very tiny corner case. I'll close this for now, but please re-open if you hit further snags in your setup that makes the case for inclusion in modd stronger.

**Comment by wader** [comment]
@cortesi ok, will do
