### ISSUE TITLE
Compile issue on OSX: termlog.Stream

### ISSUE THREAD

**Issue by aellerton** [cortesi/modd#24]
Hi,

I'm up and running with the binary release but only because both ``go get`` and building a local copy fail with this error:

    $ go build
    # .../modd
    ./daemon.go:29: undefined: termlog.Stream

I already have ``github.com/cortesi/termlog`` so I'm not sure where to look next.

Any tips?
Thanks!

**Comment by cortesi** [comment]
Hi there! This must be a stale installation of termlog - Stream is definitely there, and everything compiles everywhere I've tried. Please do re-open if you still feel this is a problem.

**Comment by aellerton** [comment]
Yes - sorry - It was my fault. I had dependencies in my GOPATH but forgot
to git update them!
