### ISSUE TITLE
Pattern starting with ./ won't trigger

### ISSUE THREAD

**Issue by ThomasWeiser** [cortesi/modd#25]
I started with pattern like `./src/*.js`, like suggest in the Readme of [devd](https://github.com/cortesi/devd), but they don't trigger rerunning the block on file changes.

`src/*.js` works fine.
`./src/*.js` only runs on startup, but not on file changes.

modd version 0.3
Linux: `Linux arch2 4.5.4-1-ARCH #1 SMP PREEMPT Wed May 11 22:21:28 CEST 2016 x86_64 GNU/Linux`

**Comment by cortesi** [comment]
Hi there. I've clarified the docs on the path matching behaviour in modd, and will fix the README in devd. In short, this is sort of the expected behaviour - we can normalise file paths, but we can't normalise the match patterns (easily).
