### ISSUE TITLE
Any way to send no signals to daemon process

### ISSUE THREAD

**Issue by deepakjois** [cortesi/modd#28]
I am using `webpack --watch` as a daemon command in my `modd.conf` file. It appears that sending SIGHUP to webpack kills the process, which is not the behavior I want.

Webpack is capable of figuring out that files changed and do a recompile by itself. So what I really want is for the daemon process to not receive any signal. Right now, I can hack it up by sending SIGWINCH.

Here is my modd.conf FWIW:

```
src/** {
  daemon +sigwinch: webpack -d --watch
}

build/** {
  daemon: devd -m ./build
}

src/**/*.js webpack.config.babel.js !src/static/js/*.js {
  prep: node_modules/.bin/eslint --fix @mods
}
```

**Comment by deepakjois** [comment]
Maybe add an option `none` to not send any signals to daemons:

```
src/** {
  daemon +none: webpack -d --watch
}
```

**Comment by cortesi** [comment]
If you put the webpack daemon in a block without any match pattern, it will run on startup but never receive change notifications:

```
{
    daemon: webpack -d --watch src
}
```

Does this do what you want?

**Comment by deepakjois** [comment]
Yes it does. I guess I missed it in the README
