### ISSUE TITLE
Relative path from modd.conf

### ISSUE THREAD

**Issue by robbles** [cortesi/modd#31]
The documentation says:

> All file names in variables are relative to the current directory

Is it possible to run commands or change directory to the one containing the modd configuration? I found the `indir` option, but that appears to take a path relative to the current directory as well?

I thought there might be a built in variable for this, but I haven't found it in the docs or the codebase.

**Comment by cortesi** [comment]
All paths are relative to the current directory so that modd.conf files can be reused. The best way to cater for this use case is to introduce a new variable - say *@confdir* - that points to the enclosing directory of the current modd.conf file. I'd accept a patch for this.

**Comment by cortesi** [comment]
Out of curiosity, what's your use case for this?

**Comment by robbles** [comment]
@cortesi that makes sense! I'll submit a PR soon then,

The use case is having multiple modd files for different parts of a project, and wanting to run commands in them that are scoped to a particular directory.

**Comment by cortesi** [comment]
The confdir patch has now been merged. Many thanks!
