### ISSUE TITLE
Detect changes in folders [linux]

### ISSUE THREAD

**Issue by averrin** [cortesi/modd#4]
Modd ignore changes in nested folders
Tryed:

    **/*.go
    /src/**/*.go
    /src/foldername/*.go

Modd prints @mods at first run, but ignore changes.

**Comment by cortesi** [comment]
Please take a careful look at the pattern matching language. To match all go files recursively, you want:

    **/*.go

A single star only matches non path separator characters. A double star matches everything.

**Comment by averrin** [comment]
Markdown eats stars :(
This pattern Dont work

**Comment by cortesi** [comment]
Ah, ok. I've edited the original comment, and will take a look at this. Thanks for reporting.

**Comment by cortesi** [comment]
Hi there - I believe this has been fixed in master. Could you please confirm for me that you're no longer seeing this with a current checkout? Thank you fo reporting this.

**Comment by averrin** [comment]
Yeah, it works now, thanks!
