### ISSUE TITLE
Kudos for this app

### ISSUE THREAD

**Issue by klauern** [cortesi/modd#40]
I spent the better part of a day trying to understand how to use [`watchman`](https://facebook.github.io/watchman/) and didn't get anywhere.  I spent all of about 30 minutes reading and parsing your `README`, and I have a working setup that I think I can use for anything.  Just wanted to throw out a round of thanks for providing a tool that is remarkably easier to set up than other tools I have tried.

**Comment by cortesi** [comment]
Excellent. Glad you've found it useful!
