### ISSUE TITLE
Have to use sparse-checkout on windows because of '*' in some test filenames

### ISSUE THREAD

**Issue by BYUDigger** [cortesi/modd#42]
In this directory and it's sub directories there are a few files with a '*' in the filename.

https://github.com/cortesi/modd/tree/master/vendor/github.com/bmatcuk/doublestar/test

Because of this I had to use sparse-checkout on windows to be able to clone this repo.

For those interested this is the work around:

Run this command: ` git config core.sparseCheckout true`

Add this file:  `.git/info/sparse-checkout` with this in it:
```
/*
!vendor/github.com/bmatcuk/doublestar/test/```

Then you'll be able to checkout the rest of the repo normally

**Comment by cortesi** [comment]
Thanks - this has just been fixed in a dependency update.
