### ISSUE TITLE
Watching a file does not work anymore

### ISSUE THREAD

**Issue by GeertJohan** [cortesi/modd#46]
It looks like a recent change to modd broke it's ability to watch for changes on a single file on linux.

e.g. with the following mod.conf:
```
somefolder/Makefile somefolder/*.go {
    # do stuff
}
```

This used to work fine, but now breaks with `Error watching: readdirent: not a directory`. When I remove the first selector (`somefolder/Makefile`), modd runs fine.

A nasty workarround is to add an asterist, e.g.: `someolder/*Makefile`, which sill then also match `Makefile` itself. However, it's not very nice and might result in unexpected behaviour, for example when somefolder/dontMindMe.Makefile is added.

**Comment by cortesi** [comment]
Hi there. Thanks for reporting this. I've just revamped the relevant code, and added some unit tests to cover this case. Could you please confirm for me that the issue is fixed in the current master?

**Comment by GeertJohan** [comment]
I just go-getted the latest versions. I get the same error (just a bit more verbose now, as it includes the path):
`22:59:33: Error watching: could not watch path '/home/geertjohan/src/path/to/some/file': readdirent: not a directory`

**Comment by cortesi** [comment]
Heh. Let's try that again. :) I've just made some more changes in the moddwatch repo - how does it look on your end?

**Comment by GeertJohan** [comment]
Yes, looks like it's working again, thanks!
