### ISSUE TITLE
'indir: ..' somehow jumps up twice?

### ISSUE THREAD

**Issue by oponder** [cortesi/modd#69]
Hi, I'm on a mac, and trying to keep my `modd.conf` file in a directory instead of in the root folder.

So abstractly my project looks like:

```
main.go
testing/
  modd.conf
```

The reason is I have some other testing related files in that folder and I'd like to keep everything related to the test setup in one place.

I'm running into some issues though getting a setup that works. I noticed that indir is behaving a bit oddly for me.

With a conf file like:

```
{
    indir: ..
    prep: "
        echo '..' Should be in top level
        pwd
    "
}

{
    prep: "
        echo without indir, should be in root
        pwd
    "
}

{
    indir: .
    prep: "
        indir '.' should be in root
        pwd
    "
}

{
    indir: "./test"
    prep: "
        echo './test' Should be in test
        pwd
    "
}

{
    indir: ..
    prep: "
        echo '..' Should be in top level
        pwd
    "
}
```

I get the following output:

```
~/go/src/github.com/cortesi/modd (master)
$ modd -f test/indir.conf
16:07:45: prep: echo '..' Should be in top level
.. Should be in top level
/Users/oponder/go/src/github.com
>> done (10.493096ms)
16:07:45: prep: echo without indir, should be in root
without indir, should be in root
/Users/oponder/go/src/github.com/cortesi/modd
>> done (9.653504ms)
16:07:45: prep: indir '.' should be in root
/Users/oponder/go/src/github.com/cortesi/modd
"indir": executable file not found in $PATH
>> done (9.849141ms)
16:07:45: prep: echo './test' Should be in test
16:07:45: Error running prep: fork/exec /Users/oponder/go/bin/modd: no such file or directory
16:07:45: prep: echo '..' Should be in top level
.. Should be in top level
/Users/oponder/go/src/github.com
>> done (9.311909ms)
```

Notice that I am in: 

`/Users/oponder/go/src/github.com/cortesi/modd` 

and when I set `indir: ..`, pwd returns: 

`/Users/oponder/go/src/github.com/`

while I would have expected to see 

`/Users/oponder/go/src/github.com/cortesi/`

There's also a strange output for the `indir: .` case: `"indir": executable file not found in $PATH`

**Comment by cortesi** [comment]
This should be fixed in master. Thanks for reporting!
