### ISSUE TITLE
indir and prep on Windows 10 doesn't work

### ISSUE THREAD

**Issue by frederikhors** [cortesi/modd#74]
With this modd.conf on Windows 10:

```conf
web/**/*.scss {
    indir: web
    prep: pwd
}
```

or

```conf
web/**/*.scss {
    indir: .\web
    prep: pwd
}
```

or

```conf
web/**/*.scss {
    indir: ./web
    prep: pwd
}
```

I got:

```log
00:12:26: prep: pwd
00:12:26: Error running prep: fork/exec C:\Users\Fred\go\bin\modd.exe: The directory name is invalid.
```

If I use this modd.conf:

```conf
web/**/*.scss {
    indir: .
    prep: pwd
}
```

it works printing correct `pwd` but for the parent of `web` folder.

Why?

**Comment by frederikhors** [comment]
With daemon no problem at all!

**Comment by cortesi** [comment]
Hi there - this should be fixed in master. Could you please verify that for me, and re-open if there's still an issue?
