### ISSUE TITLE
Binary panics with Go 1.6rc1

### ISSUE THREAD

**Issue by sheki** [cortesi/modd#8]
panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 1 [running]:
github.com/rjeczalik/notify.(*stream).Start(0xc82008a5c0, 0x0, 0x0)
        /Users/sheki/go/src/github.com/rjeczalik/notify/watcher_fsevents_cgo.go:131 +0x270
github.com/rjeczalik/notify.(*fsevents).watch(0xc82000a3f0, 0xc820088d50, 0x23, 0x100001b00, 0x0, 0x0)
        /Users/sheki/go/src/github.com/rjeczalik/notify/watcher_fsevents.go:206 +0x313
github.com/rjeczalik/notify.(*fsevents).RecursiveWatch(0xc82000a3f0, 0xc820088d50, 0x23, 0x1b0000001b00, 0x0, 0x0)
        /Users/sheki/go/src/github.com/rjeczalik/notify/watcher_fsevents.go:258 +0x51
go.(*struct { github.com/rjeczalik/notify.watcher; github.com/rjeczalik/notify.recursiveWatcher }).RecursiveWatch(0xc82000e280, 0xc820088d50, 0x23, 0xc800001b00, 0x0, 0x0)
        <autogenerated>:50 +0x7c
github.com/rjeczalik/notify.(*recursiveTree).Watch(0xc820012140, 0xc820088d50, 0x23, 0xc82008e660, 0xc820082a78, 0x1, 0x1, 0x0, 0x0)
        /Users/sheki/go/src/github.com/rjeczalik/notify/tree_recursive.go:286 +0xad6
github.com/rjeczalik/notify.Watch(0xc820082a70, 0x5, 0xc82008e660, 0xc820082a78, 0x1, 0x1, 0x0, 0x0)
        /Users/sheki/go/src/github.com/rjeczalik/notify/notify.go:64 +0x7d
github.com/cortesi/modd/watch.Watch(0xc8200846c0, 0x2, 0x2, 0x5f5e100, 0xc82008e420, 0xc8200846c0, 0x0, 0x0)
        /Users/sheki/go/src/github.com/cortesi/modd/watch/watch.go:301 +0x145
github.com/cortesi/modd.runOnChan(0xc82008e420, 0x4379e90, 0x4b40258, 0xc82008a4c0, 0xc8200844a0, 0x42ffaa0, 0xb, 0xc820053db8, 0x0, 0x0, ...)
        /Users/sheki/go/src/github.com/cortesi/modd/modd.go:89 +0x4d6
github.com/cortesi/modd.Run(0x4b40258, 0xc82008a4c0, 0xc8200844a0, 0x42ffaa0, 0xb, 0xc820053db8, 0x0, 0x0, 0x40, 0x0, ...)
        /Users/sheki/go/src/github.com/cortesi/modd/modd.go:141 +0xbe
main.main()
        /Users/sheki/go/src/github.com/cortesi/modd/cmd/modd/main.go:102 +0x9a2
☁  api [master] ⚡ kill -9 51509
☁  api [master] ⚡ GODEBUG=cgocheck=0 modd

I can get this working with 

GODEBUG=cgocheck=0 modd

**Comment by cortesi** [comment]
Hey there. This is a known issue in the notify library. There's a ticket at https://github.com/rjeczalik/notify/issues/90. I'll leave this ticket open in case anyone else comes across this.

**Comment by cortesi** [comment]
Notify has fixed this issue. We're now good for 1.6.
