### ISSUE TITLE
main.go:70:6: r.KillTimeout undefined (type *interp.Runner has no field or method KillTimeout)

### ISSUE THREAD

**Issue by Dexus** [cortesi/modd#89]
`main.go:70:6: r.KillTimeout undefined (type *interp.Runner has no field or method KillTimeout)`

I don't think it need more words...

**Comment by wader** [comment]
Might be #77

**Comment by cortesi** [comment]
Hi there. Please install with:

```
$ env GO111MODULE=on go get github.com/cortesi/modd/cmd/modd
```
