### ISSUE TITLE
fmt.Printf isn't output when running inside modd (go run)

### ISSUE THREAD

**Issue by iangregsondev** [cortesi/modd#92]
Hi,

can anyon help ? I have a really strange issue. I am outputting something using printf and if I run it without modd then all is fine but if I run it with modd then I don't see it until I make a change in the source code of the application and forces a restart (println works without having to make a change :-)  - it seems related to printf )

A simple line in main.go

```
	fmt.Printf("This should print out in main.go %s", "yes")
```

my modd config

```
**/*.go {
    daemon +sigint: go run ./cmd/exporter/. -c ./cmd/exporter/config/exporter-config.yml
}
```

and

```
modd -f ./cmd/exporter/modd.conf
```

I must be doing something strange ?

If I run the above then I get no output from the printf, but if i just run it without modd then everything works i.e.

```
go run ./cmd/exporter/. -c ./cmd/exporter/config/exporter-config.yml
```

Has anybody come across this ?

**Comment by iangregsondev** [comment]
Here is what happens when I make a change to my source code, it restarts the app as expected BUT that is when I get the output of print.

![image](https://user-images.githubusercontent.com/2370364/97420272-64b74880-190b-11eb-9281-1ad4873ae151.png)

**Comment by wader** [comment]
It could be because of line buffering or that modd reads whole lines (https://github.com/cortesi/modd/blob/master/shell/shell.go#L167 seems so). So try change to `fmt.Printf("This should print out in main.go %s\n", "yes")`

**Comment by iangregsondev** [comment]
Hi @wader , thanks for the quick response.

yes that's it, adding the "\n" works. I was about to upload a repo :-)

Can this be fixed ? Or do I have to change all my printf's to include a line break. This one is not an issue but for sure there are use cases in the future that this wouldn't be great.

Is there a work around ?

**Comment by wader** [comment]
Great! i think it's hard to fix as modd wants to log whole lines for each sub process so it has to read until there is a new line character or until EOF. In other cases you might have to flush buffers on to write side (fmt.Printf i think will end up doing write directly without a buffer) and the read side has to not be doing some kind of buffering

**Comment by iangregsondev** [comment]
Ok thanks @wader , noted, i will use a new line. At the end of the day, I only use it while developing. I will close this.

Thanks for the help and quick responses.
