### ISSUE TITLE
New release with go module

### ISSUE THREAD

**Issue by roopakv** [cortesi/modd#96]
This tool is installable via brew. To maintain support with go1.17 when it comes out and to make brew maintenance easier please release a new version of the tool which has the switch to go modules.

**Comment by joncalhoun** [comment]
Are there known issues blocking a go modules compatible version? I am willing to look into this if it would help.

**Comment by frederikhors** [comment]
> release a new version of the tool which has the switch to go modules

What does this mean?

**Comment by frou** [comment]
> What does this mean?

Presumably that the latest tagged release of modd (v0.8 from Jan 2019) is from before the project started being/using Go modules ([Aug 2019](https://github.com/cortesi/modd/commit/093e000671c4f69483e7d56de8c9db465ca67270))

**Comment by fgm** [comment]
Can this be the cause of this error when installing with homebrew ? 
```
 brew install modd
Warning: modd has been deprecated because it is not maintained upstream
```

**Comment by Fontinalis** [comment]
> Can this be the cause of this error when installing with homebrew ?
> 
> ```
>  brew install modd
> Warning: modd has been deprecated because it is not maintained upstream
> ```

I'm facing the same warning
