### ISSUE TITLE
accessing environment variables

### ISSUE THREAD

**Issue by amery** [cortesi/modd#97]
keeping in mind you use a sh interpreter, what's the right way of accessing environment variables from mood rules?
I've tried `$FOO`, `${FOO}` and `"${FOO}"` without luck. please

**Comment by wader** [comment]
Hi, can you give an example of what your trying? you should be able to do something like this for `prep` and `daemon`.
```
{
    prep: echo $USER
}
```

**Comment by amery** [comment]
@wader ok, works on prep, doesn't on daemon

**Comment by wader** [comment]
Aha ok, strange, would have expected them to be very similar. maybe a workaround is:
```
{
   daemon: sh -c "echo $USER"
}
```

**Comment by amery** [comment]
problem with that approach is you supervise the shell and not the actual daemon :-/

**Comment by wader** [comment]
Would `sh -c "exec ..."` work? think i've used that to make signals work properly etc

**Comment by amery** [comment]
dirty but should work. thanks @wader. still seems like a bug though

now that I caught you attention, another two questions:
1) how do I reference all the watched files and not only those modified?
2) is there a magic variable for the config file name?

**Comment by wader** [comment]
Hmm strange, env var seems to work for me i daemon
```sh
$ cat modd.conf
{
    prep: echo prep $USER
    daemon: echo daemon $USER
}
$ modd -f modd.conf
22:06:55: prep: echo prep $USER
prep wader
>> done (10.148971ms)
22:06:55: daemon: echo daemon $USER
>> starting...
daemon wader
exited: exit status 0
```

**Comment by amery** [comment]
I don't get it, now it seems to work for me too :-/ wth

**Comment by wader** [comment]
Don't think there such a variable, but there is `@mods`:

> `@mods` On first run, all files matching the block patterns. On subsequent change, a list of all modified files.

Maybe you can save it to file etc one first start?

```
{
  prep: rm -f /tmp/files
}

bla {
  prep: if [ ! -e /tmp/file ] ; then echo @mods > /tmp/files ; fi
  prep: echo all files $(cat /tmp/files)
}
```

**Comment by amery** [comment]
> I don't get it, now it seems to work for me too :-/ wth

I found the culprit, a missing \ after `env GO=$(GO)` on a Makefile :man_facepalming: 

> Maybe you can save it to a file etc on first start?

currently I'm using find + xargs, but it feels so redundant :shame:
```
assets/**.js assets/**.css {
        prep: cd assets; find * -name *.js -o -name *.css | xargs -t file2go -o files.go -p assets
}
```
